import { parseFixedSurveySettings } from "@/lib/survey";
import { updateFixedSurveySettings } from "./actions";

export function FixedSurveyEditor({ id, templateKey, value }: { id: string; templateKey: string; value: unknown }) {
  const settings = parseFixedSurveySettings(value);
  const isOneTime = templateKey === "ONE_TIME_DONATION";
  return <form action={updateFixedSurveySettings} className="mt-8 grid gap-5 rounded-xl border border-sky-200 bg-sky-50 p-5"><input name="id" type="hidden" value={id} /><div><h2 className="text-2xl font-bold text-slate-900">Vaste inhoud aanpassen</h2><p className="mt-1 text-sm text-slate-700">De technische werking blijft hetzelfde; deze teksten en labels mag u vrij aanpassen.</p></div>
    {isOneTime ? <div className="grid gap-4 rounded-lg bg-white p-4"><p className="rounded-md bg-amber-100 p-3 text-sm font-bold text-amber-900">Mollie is tijdelijk uitgeschakeld. Naam en bedrag worden tijdens de test alleen opgeslagen.</p><label>Kop boven de velden<input defaultValue={settings.oneTimeHeading} maxLength={500} name="oneTimeHeading" required /></label><div className="grid gap-4 sm:grid-cols-2"><label>Label naamveld<input defaultValue={settings.oneTimeNameLabel} maxLength={500} name="oneTimeNameLabel" required /></label><label>Label bedragveld<input defaultValue={settings.oneTimeAmountLabel} maxLength={500} name="oneTimeAmountLabel" required /></label></div><label>Voorbeeld in bedragveld<input defaultValue={settings.oneTimeAmountPlaceholder} maxLength={500} name="oneTimeAmountPlaceholder" required /></label><input name="oneTimeSubmitLabel" type="hidden" value={settings.oneTimeSubmitLabel} /><label>Tekst onderaan<textarea defaultValue={settings.privacyText} maxLength={500} name="privacyText" rows={3} /></label></div>
    : <><div className="grid gap-4 rounded-lg bg-white p-4"><h3 className="font-bold">Persoonsgegevens</h3><label>Kop<input defaultValue={settings.contactHeading} name="contactHeading" required /></label><div className="grid gap-4 sm:grid-cols-2"><label>Voornaamlabel<input defaultValue={settings.firstNameLabel} name="firstNameLabel" required /></label><label>Achternaamlabel<input defaultValue={settings.lastNameLabel} name="lastNameLabel" required /></label><label>Telefoonlabel<input defaultValue={settings.phoneLabel} name="phoneLabel" required /></label><label>E-maillabel<input defaultValue={settings.emailLabel} name="emailLabel" required /></label></div></div>
      <div className="grid gap-4 rounded-lg bg-white p-4"><h3 className="font-bold">Vragen en antwoordknoppen</h3><label>Vraag 1<textarea defaultValue={settings.question1} name="question1" required rows={2} /></label><label>Vraag 2<textarea defaultValue={settings.question2} name="question2" required rows={2} /></label><div className="grid gap-4 sm:grid-cols-2"><label>Ja-knop<input defaultValue={settings.yesLabel} name="yesLabel" required /></label><label>Nee-knop<input defaultValue={settings.noLabel} name="noLabel" required /></label><label>Ja bij lid worden<input defaultValue={settings.joinYesLabel} name="joinYesLabel" required /></label><label>Nee bij lid worden<input defaultValue={settings.joinNoLabel} name="joinNoLabel" required /></label></div></div>
      <div className="grid gap-4 rounded-lg bg-white p-4"><h3 className="font-bold">Meldingen en machtiging</h3><label>Melding voor bestaande donateur<textarea defaultValue={settings.existingDonorNote} name="existingDonorNote" rows={2} /></label><label>Melding bij niet lid worden<textarea defaultValue={settings.noMembershipNote} name="noMembershipNote" rows={2} /></label><label>Label maandbedrag<input defaultValue={settings.monthlyAmountLabel} name="monthlyAmountLabel" required /></label><label>Toestemmingstekst<textarea defaultValue={settings.consentText} maxLength={1000} name="consentText" required rows={4} /></label><label>Tekst op verzendknop<input defaultValue={settings.submitLabel} name="submitLabel" required /></label><label>Tekst onderaan<textarea defaultValue={settings.privacyText} name="privacyText" rows={3} /></label></div></>}
    <button className="w-fit rounded-md bg-[#1483d6] px-5 py-3 font-bold text-white" type="submit">Vaste inhoud opslaan</button>
  </form>;
}
