import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { absoluteUrl } from "@/lib/seo";
import { formatCurrency, formatDate } from "@/lib/display";
import { CUSTOM_SURVEY_TEMPLATE_KEY, parseSurveyQuestions, surveyStatusLabel, type DonorSurveyAnswers, type OneTimeDonationAnswers } from "@/lib/survey";
import { deleteSurvey, updateSurvey, updateSurveyQuestions } from "../actions";
import { CopySurveyLink, DeleteSurveyButton } from "../SurveyAdminControls";
import { SurveyQuestionBuilder } from "../SurveyQuestionBuilder";

export const dynamic = "force-dynamic";
function yesNo(value: boolean | null) { return value === null ? "-" : value ? "Ja" : "Nee"; }
function dateInput(value: Date | null) { return value ? value.toISOString().slice(0, 10) : ""; }
function answerText(value: unknown) { return Array.isArray(value) ? value.join(", ") : value === null || value === undefined || value === "" ? "-" : String(value); }

export default async function SurveyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const survey = await prisma.survey.findUnique({ where: { id }, include: { responses: { orderBy: { submittedAt: "desc" }, include: { donationPayment: true } } } });
  if (!survey) notFound();
  const url = absoluteUrl(`/enquete/${survey.slug}`);
  const isOneTime = survey.templateKey === "ONE_TIME_DONATION";
  const isCustom = survey.templateKey === CUSTOM_SURVEY_TEMPLATE_KEY;
  const questions = parseSurveyQuestions(survey.questions);
  const typeLabel = isCustom ? "Zelfgemaakt formulier" : isOneTime ? "Eenmalige donatie" : "Donateurschap en maandelijkse donatie";

  return <main className="mx-auto max-w-7xl px-4 py-10">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#0f766e]">Enquête beheren</p><h1 className="text-3xl font-bold text-slate-900">{survey.title}</h1><p className="mt-2 text-slate-700">{typeLabel} · Status: <strong>{surveyStatusLabel(survey)}</strong> · {survey.responses.length} antwoorden</p></div><div className="flex flex-wrap gap-3"><CopySurveyLink url={url} /><a className="rounded-md bg-[#1483d6] px-4 py-3 font-semibold text-white" download href={`/admin/settings/surveys/${survey.id}/qr`}>QR-code downloaden</a></div></div>
    <section className="mt-6 rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="text-sm font-bold text-emerald-900">Unieke openbare link</p><a className="mt-1 block break-all font-semibold text-[#0f5f9f] underline" href={url} rel="noreferrer" target="_blank">{url}</a></section>
    <form action={updateSurvey} className="mt-6 grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><input name="id" type="hidden" value={survey.id} /><h2 className="text-xl font-bold">Instellingen</h2><label>Titel<input defaultValue={survey.title} name="title" required /></label><label>Toelichting<textarea defaultValue={survey.description ?? ""} name="description" rows={3} /></label><label className="flex grid-cols-none flex-row items-center gap-3"><input className="w-auto" defaultChecked={!survey.startsAt && !survey.endsAt} name="unlimited" type="checkbox" /> Onbeperkt beschikbaar</label><div className="grid gap-4 sm:grid-cols-2"><label>Begindatum<input defaultValue={dateInput(survey.startsAt)} name="startsAt" type="date" /></label><label>Einddatum<input defaultValue={dateInput(survey.endsAt)} name="endsAt" type="date" /></label></div><label className="flex grid-cols-none flex-row items-center gap-3"><input className="w-auto" defaultChecked={survey.isActive} name="isActive" type="checkbox" /> Enquête actief</label><button className="w-fit rounded-md bg-[#1483d6] px-4 py-3 font-semibold text-white" type="submit">Instellingen opslaan</button></form>
    {isCustom ? <form action={updateSurveyQuestions} className="mt-8 grid gap-4"><input name="id" type="hidden" value={survey.id} /><div><h2 className="text-2xl font-bold text-slate-900">Vragen bewerken</h2><p className="mt-1 text-sm text-slate-600">Nieuwe antwoorden gebruiken direct de aangepaste vragenlijst. Bestaande antwoorden blijven bewaard.</p></div><SurveyQuestionBuilder initialQuestions={questions} /><button className="w-fit rounded-md bg-[#1483d6] px-5 py-3 font-bold text-white" type="submit">Vragen opslaan</button></form> : null}
    <section className="mt-8"><h2 className="text-2xl font-bold text-slate-900">Antwoorden</h2>{survey.responses.length ? <div className="mt-4 overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-sm">
      {isCustom ? <table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Datum</th>{questions.map((question) => <th className="p-3" key={question.id}>{question.title}</th>)}</tr></thead><tbody>{survey.responses.map((response) => { const answers = response.answers as Record<string, unknown>; return <tr className="border-t border-slate-200" key={response.id}><td className="whitespace-nowrap p-3">{formatDate(response.submittedAt)}</td>{questions.map((question) => <td className="p-3" key={question.id}>{answerText(answers[question.id])}</td>)}</tr>; })}</tbody></table>
      : isOneTime ? <table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Datum</th><th className="p-3">Naam</th><th className="p-3">Bedrag</th><th className="p-3">Betaalstatus</th><th className="p-3">Mollie-nummer</th></tr></thead><tbody>{survey.responses.map((response) => { const answers = response.answers as OneTimeDonationAnswers; return <tr className="border-t border-slate-200" key={response.id}><td className="p-3">{formatDate(response.submittedAt)}</td><td className="p-3 font-semibold">{response.firstName}</td><td className="p-3">{answers.oneTimeAmountCents === null ? "-" : formatCurrency(answers.oneTimeAmountCents)}</td><td className="p-3 font-semibold">{response.donationPayment?.status === "paid" ? "Betaald" : response.donationPayment?.status ?? "Niet gestart"}</td><td className="p-3 text-xs">{response.donationPayment?.molliePaymentId ?? "-"}</td></tr>; })}</tbody></table>
      : <table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Datum</th><th className="p-3">Voornaam</th><th className="p-3">Achternaam</th><th className="p-3">Mobiel</th><th className="p-3">E-mail</th><th className="p-3">Al donateur</th><th className="p-3">Wil donateur worden</th><th className="p-3">Maandelijks doneren</th><th className="p-3">Bedrag</th><th className="p-3">Toestemming</th></tr></thead><tbody>{survey.responses.map((response) => { const answers = response.answers as DonorSurveyAnswers; return <tr className="border-t border-slate-200" key={response.id}><td className="p-3">{formatDate(response.submittedAt)}</td><td className="p-3 font-semibold">{response.firstName}</td><td className="p-3 font-semibold">{response.lastName}</td><td className="p-3">{response.phone}</td><td className="p-3">{response.email}</td><td className="p-3">{yesNo(answers.isExistingDonor)}</td><td className="p-3">{yesNo(answers.wantsToBecomeDonor)}</td><td className="p-3">{yesNo(answers.wantsMonthlyDonation)}</td><td className="p-3">{answers.monthlyAmountCents === null ? "-" : formatCurrency(answers.monthlyAmountCents)}</td><td className="p-3">{answers.directDebitConsent ? "Ja" : "-"}</td></tr>; })}</tbody></table>}
    </div> : <div className="mt-4 rounded-lg border border-slate-200 bg-white p-8 text-center text-slate-600">Er zijn nog geen antwoorden ontvangen.</div>}</section>
    <form action={deleteSurvey} className="mt-10 border-t border-slate-200 pt-6"><input name="id" type="hidden" value={survey.id} /><DeleteSurveyButton /></form>
  </main>;
}
