"use client";

import { useState } from "react";
import { createSurvey } from "../actions";

export function NewSurveyForm({ canCreateMembership }: { canCreateMembership: boolean }) {
  const [template, setTemplate] = useState<"DONOR_JOURNEY" | "ONE_TIME_DONATION">(canCreateMembership ? "DONOR_JOURNEY" : "ONE_TIME_DONATION");
  return <form action={createSurvey} className="mt-8 grid gap-5">
    <section className="grid gap-3 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Wat wilt u aanmaken?</h2>{canCreateMembership ? <label className="flex grid-cols-none flex-row items-start gap-3 rounded-lg border p-4"><input checked={template === "DONOR_JOURNEY"} className="mt-1 w-auto" name="templateKey" onChange={() => setTemplate("DONOR_JOURNEY")} type="radio" value="DONOR_JOURNEY" /><span><strong>Vaste lidmaatschapsenquête</strong><span className="mt-1 block text-sm font-normal text-slate-600">Direct klaar met verificatiecode, opnieuw versturen, verhogen en opzeggen. Er kan maar één bestaan.</span></span></label> : <p className="rounded-md bg-emerald-50 p-3 text-sm font-bold text-emerald-900">De vaste lidmaatschapsenquête bestaat al en kan via het overzicht worden beheerd.</p>}<label className="flex grid-cols-none flex-row items-start gap-3 rounded-lg border p-4"><input checked={template === "ONE_TIME_DONATION"} className="mt-1 w-auto" name="templateKey" onChange={() => setTemplate("ONE_TIME_DONATION")} type="radio" value="ONE_TIME_DONATION" /><span><strong>Eenmalige donatie</strong><span className="mt-1 block text-sm font-normal text-slate-600">Maak een doel zoals Fitrah of Donatie voor imam.</span></span></label></section>
    {template === "DONOR_JOURNEY" ? <section className="grid gap-4 rounded-lg border border-sky-200 bg-sky-50 p-5"><h2 className="text-xl font-bold">Vaste lidmaatschapsenquête</h2><p className="text-sm text-slate-700">Alle vragen en de volledige beveiligde vervolglogica worden automatisch ingesteld. Het formulier wordt direct gepubliceerd en vervalt nooit.</p><input name="title" type="hidden" value="Lidmaatschap Masjid Ghausia" /><input name="description" type="hidden" value="Aanmelden als maandelijkse donateur of uw bestaande donateurschap beheren." /><input name="unlimited" type="hidden" value="on" /></section> : <><section className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><label>Waar is de donatie voor bedoeld?<input name="title" required placeholder="Bijvoorbeeld Fitrah of Donatie voor imam" /></label><label>Korte uitleg (optioneel)<textarea name="description" rows={3} placeholder="Leg kort uit waarvoor de donatie wordt gebruikt" /></label></section><section className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Looptijd</h2><label className="flex grid-cols-none flex-row items-center gap-3"><input className="w-auto" defaultChecked name="unlimited" type="checkbox" /> Onbeperkt beschikbaar</label><div className="grid gap-4 sm:grid-cols-2"><label>Begindatum<input name="startsAt" type="date" /></label><label>Einddatum<input name="endsAt" type="date" /></label></div></section><section className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Na verzending</h2><label>Eigen bedanktekst<textarea name="thankYouMessage" placeholder="Bedankt voor uw donatie." rows={3} /></label><label>E-mailmelding naar (optioneel)<input name="notificationEmail" placeholder="bijvoorbeeld sgbc16@gmail.com" type="email" /></label><label>Automatisch sluiten na aantal donaties<input min="1" name="maxResponses" placeholder="Leeg laten voor onbeperkt" type="number" /></label><input name="identityMode" type="hidden" value="OPTIONAL" /><p className="rounded-md bg-slate-50 p-3 text-sm text-slate-700">De donateur kiest op het formulier zelf tussen naam invullen en anoniem doneren.</p><p className="text-sm font-semibold text-amber-800">De campagne wordt eerst als concept opgeslagen. Bekijk het voorbeeld en publiceer hem daarna.</p></section></>}
    <button className="rounded-md bg-[#1483d6] px-4 py-3 font-semibold text-white" type="submit">{template === "DONOR_JOURNEY" ? "Vaste enquête aanmaken" : "Donatiecampagne maken"}</button>
  </form>;
}
